### ISSUE TITLE
FeatureRequest: Commitizen pre-commit hooks

### ISSUE THREAD

**Issue by kenibrewer** [cytomining/pycytominer#345]
### Feature type

- [X] Add new functionality

- [ ] Change existing functionality

### General description of the proposed functionality

Adding commitizen pre-commit hooks will ensure that all commits are properly formatted for updating the CHANGELOG. However, there are potential side-effects of these hooks:

> What would happen to PR's which don't abide this (would we disapprove solely based on the commit style)?
> Thinking about the end of the PR and getting ready to merge: how are squashes treated with this (would we lose the ability to leverage GitHub's built-in functionality here)?

_Originally posted by @d33bs in https://github.com/cytomining/pycytominer/pull/340#discussion_r1374868916_

### Feature example

Commitizen provides two hooks as show below:

```yaml
  - repo: https://github.com/commitizen-tools/commitizen
    rev: master
    hooks:
      - id: commitizen
      - stages: [pre-commit]
      - id: commitizen-branch
        stages: [push]
```

The `commitizen` hook prevents commits from being completed if they aren't formatted correctly. 
The `commitzen-branch` hook will check all of the commits of a branch prior to them being pushed to the repo. 

### Alternative Solutions

- Clear guidance in the CONTRIBUTING.md file
- Can pre-commit be set to "raise warnings"?
- Simply have maintainers fix commit messages when merging branches 
- Provide guidance on how to bypass the hooks for people who need that
