### ISSUE TITLE
FeatureRequest: Add build artifacts for CI/CD pipeline

### ISSUE THREAD

**Issue by kenibrewer** [cytomining/pycytominer#369]
### Feature type

- [X] Add new functionality

- [ ] Change existing functionality

### General description of the proposed functionality

Add additional steps to Github Actions workflow that will build a properly-versioned code artifact using `poetry build` instead of the "version-less" copy of the source code currently generated. These code artifacts can be used in the following ways:

1. Include new build artifacts in the Github release alongside the existing source code tarball. 
2. Drops the need for `poetry-dynamic-versioning` and a full git history in:
- Docker images 
- Dependent Github actions workflows. 

### Feature example

```yaml 
- step: build wheel/sdist
  run: poetry build
- step: upload-artifact 
  with: https://github.com/actions/upload-artifact

- step: build docker image
  with: download-artifact
- step: unpack artifact
- step: build docker image
```

### Additional information

We should also add a section to `pyproject.toml` that includes files we want/need in our build artifact such as the `tests` directory. 

See: https://python-poetry.org/docs/pyproject/#include-and-exclude
